<link rel="stylesheet" type="text/css"
    href="<?php echo $block->getViewFileUrl('Magento_Theme::css/owl.carousel.min.css')?>">
<link rel="stylesheet" type="text/css"
    href="<?php echo $block->getViewFileUrl('Magento_Theme::css/owl.theme.default.min.css')?>">

<div id="owl-demo" class="owl-carousel owl-theme">
    <div class="item">
        <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/img-slide_01.jpg'); ?>" />
        <div class="custom-slider-wrapper">
            <div class="custom-slider-inner">
                <div class="custom-slider">
                    <div class="heading-title poppins-font bold">
                        <h2>Dumbbells Shop</h2>
                    </div>
                    <div class="sub-title poppins-font bold">
                        <h3>Best body fitness</h3>
                    </div>
                    <div class="description poppins-font">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
                        has been the
                        industry's standard dummy text ever since the 1500s, when an unknown printer
                    </div>
                    <button class="poppins-font">Shop now</button>
                </div>
            </div>
        </div>
    </div>
    <div class="item">
        <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/img-slide_01.jpg'); ?>" />
        <div class="custom-slider-wrapper">
            <div class="custom-slider-inner">
                <div class="custom-slider">
                    <div class="heading-title poppins-font bold">
                        <h2>Dumbbells Shop</h2>
                    </div>
                    <div class="sub-title poppins-font bold">
                        <h3>Best body fitness</h3>
                    </div>
                    <div class="description poppins-font">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
                        has been the
                        industry's standard dummy text ever since the 1500s, when an unknown printer
                    </div>
                    <button class="poppins-font">Shop now</button>
                </div>
            </div>
        </div>
    </div>
    <div class="item">
        <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/img-slide_01.jpg'); ?>" />
        <div class="custom-slider-wrapper">
            <div class="custom-slider-inner">
                <div class="custom-slider">
                    <div class="heading-title poppins-font bold">
                        <h2>Dumbbells Shop</h2>
                    </div>
                    <div class="sub-title poppins-font bold">
                        <h3>Best body fitness</h3>
                    </div>
                    <div class="description poppins-font">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
                        has been the
                        industry's standard dummy text ever since the 1500s, when an unknown printer
                    </div>
                    <button class="poppins-font">Shop now</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
    "*": {
        "slider": {}
    }
}
</script>