<section class="section2">
    <div class="item order-md-1 order-xs-1">
        <img src="<?php echo $this->getViewFileUrl('images/item1_23.jpg'); ?>" /> 
    </div>
    <div class="item-description-wrapper order-md-3 order-xs-4">
        <div class="item-description-inner">
            <div class="item-icon">
                <img src="<?php echo $this->getViewFileUrl('images/item-icon2_26.png'); ?>" /> 
            </div>
            <div class="item-title poppins-font bold">
                Strength
            </div>
            <div class="item-description poppins-font">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            </div>
        </div>
    </div>
    <div class="item order-md-5 order-xs-5">
        <img src="<?php echo $this->getViewFileUrl('images/item3_25.png'); ?>" /> 
    </div>
    <div class="item-description-wrapper order-md-2 order-xs-2">
        <div class="item-description-inner">
            <div class="item-icon">
                <img src="<?php echo $this->getViewFileUrl('images/item-icon1_31.png'); ?>" /> 
            </div>
            <div class="item-title poppins-font bold">
                dumbbells
            </div>
            <div class="item-description poppins-font">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            </div>
        </div>
    </div>
    <div class="item order-md-4 order-xs-3">
        <img src="<?php echo $this->getViewFileUrl('images/item2_32.jpg'); ?>" /> 
    </div>
    <div class="item-description-wrapper order-md-6 order-xs-6">
        <div class="item-description-inner">
            <div class="item-icon">
                <img src="<?php echo $this->getViewFileUrl('images/item-icon3_34.jpg'); ?>" /> 
            </div>
            <div class="item-title poppins-font bold">
                power rack & cages
            </div>
            <div class="item-description poppins-font">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            </div>
        </div>
    </div>
</section>